### ISSUE TITLE
Error with Connext on Member Center staging.

### ISSUE THREAD

**Issue by sframe** [mg2connext/connext#17]
Hi Dael,

Can you assist us on the error we are seeing?

http://membercenter-staging.ajc.com/edit-profile

`XMLHttpRequest cannot load https://stage-api.mg2connext.com/api/configuration/siteCode/AJC/configCode/CFG_TEST. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://membercenter-staging.ajc.com' is therefore not allowed access.`

**Comment by sframe** [comment]
@mkoza178 : Hey Marc, I think we missed the Dael window ;)

Is this something you can help us out with?

Thanks!

**Comment by barchito** [comment]
seems like your website is not under https and connext api is under https. My recommendation will be to load the page using https. 

The error is happening because CORS is not allowed between http and https. Should be all http or all https.

Thanks,
Gabriel

**Comment by sframe** [comment]
@barchito - thanks for the quick response. I'll look into how we're loading connext.

**Comment by NatalliaMikhailava** [comment]
http://prntscr.com/faq9nx
1.0 is not supported anymore. 1.3 version or higher should be used

**Comment by NatalliaMikhailava** [comment]
Hi, team!

Has this been resolved?

**Comment by willist** [comment]
This has been resolved, but seeing a new error now:

```
Core getConfiguration Connext.API.GetLastPublishDateS3.Done => parseJSON <<EXCEPTION>> TypeError: Cannot read property 'GUPAccountService' of undefined
    at Object.init (http://cdn.mg2connext.com/stage/1.6/Connext.min.js:1:99969)
    at http://cdn.mg2connext.com/stage/1.6/Connext.min.js:1:128896
    at i (https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js:2:27983)
    at Object.fireWith [as resolveWith] (https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js:2:28749)
    at Object.f.(anonymous function) [as resolve] (https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js:2:30897)
    at Object.<anonymous> (http://cdn.mg2connext.com/stage/1.6/Connext.min.js:1:130392)
    at i (https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js:2:27983)
    at Object.fireWith [as resolveWith] (https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js:2:28749)
    at A (https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js:4:14203)
    at XMLHttpRequest.<anonymous> (https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js:4:16491)
(anonymous) @ Connext.min.js:1
```

**Comment by willist** [comment]
This can be observed on http://membercenter-staging.ajc.com/.

**Comment by willist** [comment]
Just wanted to follow up on this. This error is preventing all actions from firing, so I'm not able to work on Connext related items until this is resolved.

cc @sframe

**Comment by NatalliaMikhailava** [comment]
We are looking into this. Will update you with results today

**Comment by NatalliaMikhailava** [comment]
This is fixed

**Comment by willist** [comment]
Looks good. Thank you!
